# Generated by Django 2.0.4 on 2018-07-27 12:12

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('rated', models.TextField()),
                ('released', models.TextField()),
                ('runtime', models.TextField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('awards', models.TextField()),
                ('poster', models.TextField()),
                ('ratings1', picklefield.fields.PickledObjectField(editable=False)),
                ('metascore', models.FloatField()),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.FloatField()),
                ('imdb_id', models.IntegerField()),
                ('type', models.TextField()),
                ('dvd', models.TextField()),
                ('boxoffice', models.TextField()),
                ('production', models.TextField()),
                ('website', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
