# Generated by Django 2.0.4 on 2018-07-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdb_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_votes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='metascore',
            field=models.TextField(),
        ),
    ]
