# Generated by Django 2.0.4 on 2018-07-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_auto_20180727_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesapp.Movies')),
            ],
        ),
    ]
