# Generated by Django 2.0.4 on 2018-07-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ratings1',
        ),
        migrations.AddField(
            model_name='movies',
            name='ratings',
            field=models.TextField(default=None),
        ),
    ]
