# Generated by Django 2.0.4 on 2018-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ratings',
            field=models.TextField(),
        ),
    ]
